In [36]:
import pandas as pd
movielens_df=pd.read_csv(
    r"C:\Users\aksha\OneDrive\Desktop\REBEM\movielens_final.csv")

In [37]:
movielens_df.head()

,Unnamed: 0,user_id,item_id,rating,age,gender,occupatioin,title,release_date,genre_label
0,0,196,242,3,49,M,writer,Kolya (1996),24-Jan-1997,Comedy
1,1,186,302,3,39,F,executive,L.A. Confidential (1997),01-Jan-1997,Crime|Film-Noir|Mystery|Thriller
2,2,22,377,1,25,M,writer,Heavyweights (1994),01-Jan-1994,Children's|Comedy
3,3,244,51,2,28,M,technician,Legends of the Fall (1994),01-Jan-1994,Drama|Romance|War|Western
4,4,166,346,1,47,M,educator,Jackie Brown (1997),01-Jan-1997,Crime|Drama

In [38]:
tmdb_df=pd.read_csv(
    r"C:\Users\aksha\OneDrive\Desktop\REBEM\movies_tmdb123.csv")

In [39]:
tmdb_df.head()

,Unnamed: 0,tmdb_id,title,release_date,release_year,language,genres,popularity,vote_average,vote_count,overview,genre_labels
0,0,98,Gladiator,2000-05-04,2000,en,"[28, 18, 12]",21.0347,8.221,20485,"After the death of Emperor Marcus Aurelius, hi...","['Action', 'Drama', 'Adventure']"
1,1,111646,Biyaheng Langit,2000-10-25,2000,en,"[18, 28, 10749]",17.0227,2.000,2,"Biyaheng Langit tells the story of Bea, a youn...","['Drama', 'Action', 'Romance']"
2,2,107,Snatch,2000-09-01,2000,en,"[80, 35]",14.6372,7.816,9731,"Unscrupulous boxing promoters, violent bookies...","['Crime', 'Comedy']"
3,3,11688,The Emperor's New Groove,2000-12-15,2000,en,"[12, 16, 35, 10751, 14]",14.7474,7.558,7162,Emperor Kuzco is turned into a llama by his ex...,"['Adventure', 'Animation', 'Comedy', 'Family',..."
4,4,1359,American Psycho,2000-01-21,2000,en,"[53, 18, 80]",14.5561,7.406,11963,A wealthy New York investment banking executiv...,"['Thriller', 'Drama', 'Crime']"

In [40]:
GENRE_NORMALIZATION_MAP = {
    "Sci-Fi": "Science Fiction",
    "Musical": "Music",
    "Children's": "Family"
}

In [41]:
def normalize_genre(genres):
    if not isinstance(genres,list):
        return "unknown"
    if len(genres)==0:
        return "unknown"
    normalized={
        GENRE_NORMALIZATION_MAP.get(g,g)
        for g in genres
    }
    return list(normalized)

In [42]:
type(tmdb_df["genre_labels"].iloc[0])

str

In [43]:
import ast
tmdb_df["genre_labels"]=tmdb_df["genre_labels"].apply(
    lambda x:ast.literal_eval(x) if isinstance(x,str) else x)

In [44]:
type(tmdb_df["genre_labels"].iloc[0])

list

In [45]:
tmdb_df["genre_labels"]=tmdb_df["genre_labels"].apply(normalize_genre)

In [46]:
tmdb_df.head()

,Unnamed: 0,tmdb_id,title,release_date,release_year,language,genres,popularity,vote_average,vote_count,overview,genre_labels
0,0,98,Gladiator,2000-05-04,2000,en,"[28, 18, 12]",21.0347,8.221,20485,"After the death of Emperor Marcus Aurelius, hi...","[Adventure, Drama, Action]"
1,1,111646,Biyaheng Langit,2000-10-25,2000,en,"[18, 28, 10749]",17.0227,2.000,2,"Biyaheng Langit tells the story of Bea, a youn...","[Drama, Action, Romance]"
2,2,107,Snatch,2000-09-01,2000,en,"[80, 35]",14.6372,7.816,9731,"Unscrupulous boxing promoters, violent bookies...","[Comedy, Crime]"
3,3,11688,The Emperor's New Groove,2000-12-15,2000,en,"[12, 16, 35, 10751, 14]",14.7474,7.558,7162,Emperor Kuzco is turned into a llama by his ex...,"[Fantasy, Adventure, Family, Comedy, Animation]"
4,4,1359,American Psycho,2000-01-21,2000,en,"[53, 18, 80]",14.5561,7.406,11963,A wealthy New York investment banking executiv...,"[Thriller, Drama, Crime]"

In [47]:
type(tmdb_df)

pandas.core.frame.DataFrame

In [48]:
def split_movielens_genres(genre_str):
    if genre_str == "(no genres listed)" or not genre_str:
        return ["unknown"]
    return genre_str.split("|")

In [49]:
movielens_df["genre_label"] = movielens_df["genre_label"].apply(split_movielens_genres)

In [50]:
type(movielens_df)

pandas.core.frame.DataFrame

In [51]:
movielens_df.columns

Index(['Unnamed: 0', 'user_id', 'item_id', 'rating', 'age', 'gender',
       'occupatioin', 'title', 'release_date', 'genre_label'],
      dtype='object')

In [52]:
movielens_df["genre_label"].iloc[1]

['Crime', 'Film-Noir', 'Mystery', 'Thriller']

In [53]:
movielens_df.head()

,Unnamed: 0,user_id,item_id,rating,age,gender,occupatioin,title,release_date,genre_label
0,0,196,242,3,49,M,writer,Kolya (1996),24-Jan-1997,[Comedy]
1,1,186,302,3,39,F,executive,L.A. Confidential (1997),01-Jan-1997,"[Crime, Film-Noir, Mystery, Thriller]"
2,2,22,377,1,25,M,writer,Heavyweights (1994),01-Jan-1994,"[Children's, Comedy]"
3,3,244,51,2,28,M,technician,Legends of the Fall (1994),01-Jan-1994,"[Drama, Romance, War, Western]"
4,4,166,346,1,47,M,educator,Jackie Brown (1997),01-Jan-1997,"[Crime, Drama]"

In [54]:
movielens_df["genre_label"]=movielens_df["genre_label"].apply(normalize_genre)

In [55]:
movielens_df.head(10)

,Unnamed: 0,user_id,item_id,rating,age,gender,occupatioin,title,release_date,genre_label
0,0,196,242,3,49,M,writer,Kolya (1996),24-Jan-1997,[Comedy]
1,1,186,302,3,39,F,executive,L.A. Confidential (1997),01-Jan-1997,"[Thriller, Mystery, Film-Noir, Crime]"
2,2,22,377,1,25,M,writer,Heavyweights (1994),01-Jan-1994,"[Family, Comedy]"
3,3,244,51,2,28,M,technician,Legends of the Fall (1994),01-Jan-1994,"[War, Drama, Western, Romance]"
4,4,166,346,1,47,M,educator,Jackie Brown (1997),01-Jan-1997,"[Drama, Crime]"
5,5,298,474,4,44,M,executive,Dr. Strangelove or: How I Learned to Stop Worr...,01-Jan-1963,"[War, Science Fiction]"
6,6,115,265,2,31,M,engineer,"Hunt for Red October, The (1990)",01-Jan-1990,"[Thriller, Action]"
7,7,253,465,5,26,F,librarian,"Jungle Book, The (1994)",01-Jan-1994,"[Adventure, Family, Romance]"
8,8,305,451,3,23,M,programmer,Grease (1978),01-Jan-1978,"[Romance, Music, Comedy]"
9,9,6,86,3,42,M,executive,"Remains of the Day, The (1993)",01-Jan-1993,[Drama]

In [56]:
movielens_df.drop("Unnamed: 0",axis=1)

,user_id,item_id,rating,age,gender,occupatioin,title,release_date,genre_label
0,196,242,3,49,M,writer,Kolya (1996),24-Jan-1997,[Comedy]
1,186,302,3,39,F,executive,L.A. Confidential (1997),01-Jan-1997,"[Thriller, Mystery, Film-Noir, Crime]"
2,22,377,1,25,M,writer,Heavyweights (1994),01-Jan-1994,"[Family, Comedy]"
3,244,51,2,28,M,technician,Legends of the Fall (1994),01-Jan-1994,"[War, Drama, Western, Romance]"
4,166,346,1,47,M,educator,Jackie Brown (1997),01-Jan-1997,"[Drama, Crime]"
...,...,...,...,...,...,...,...,...,...
99995,880,476,3,13,M,student,"First Wives Club, The (1996)",14-Sep-1996,[Comedy]
99996,716,204,5,36,F,administrator,Back to the Future (1985),01-Jan-1985,"[Science Fiction, Comedy]"
99997,276,1090,1,21,M,student,Sliver (1993),01-Jan-1993,[Thriller]
99998,13,225,2,47,M,educator,101 Dalmatians (1996),27-Nov-1996,"[Family, Comedy]"
99999,12,203,3,28,F,other,Unforgiven (1992),01-Jan-1992,[Western]

In [58]:
tmdb_df.to_csv(r"C:\Users\aksha\OneDrive\Desktop\REBEM\tmdb_movies.csv",index=False)

In [59]:
movielens_df.to_csv(r"C:\Users\aksha\OneDrive\Desktop\REBEM\movielens_data.csv",index=False)