In [1]:
import pandas as pd

genre_df=pd.read_csv(
    "C:\\Users\\aksha\\OneDrive\\Desktop\\movies\\archive (3)\\ml-100k\\u.genre",
    header=None,
    sep="|",
    names=["genres","genre_id"])
genre_df.head(19)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aksha\\OneDrive\\Desktop\\movies\\archive (3)\\ml-100k\\u.genre'

In [3]:
cols=["item_id","title","release_date","video_Release_date","imdb_url"]+genre_df["genres"].tolist()
movies_df=pd.read_csv(
    "C:\\Users\\aksha\\OneDrive\\Desktop\\movies\\archive (3)\\ml-100k\\u.item",
    sep="|",
    names=cols,
    header=None,
    encoding="latin-1"
)
movies_df.head()

,item_id,title,release_date,video_Release_date,imdb_url,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [4]:
genre_cols=genre_df["genres"].tolist()

In [5]:
def extract_genre(row):
    return ",".join([g for g in genre_cols if row[g]==1])

In [6]:
movies_df["genre_label"]=movies_df.apply(extract_genre,axis=1)

In [7]:
movies_df.head()

,item_id,title,release_date,video_Release_date,imdb_url,unknown,Action,Adventure,Animation,Children's,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,genre_label
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,"Animation,Children's,Comedy"
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,"Action,Adventure,Thriller"
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,Thriller
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,"Action,Comedy,Drama"
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,"Crime,Drama,Thriller"

In [8]:
movies_df.drop(["video_Release_date","imdb_url"], axis=1)

,item_id,title,release_date,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,genre_label
0,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,"Animation,Children's,Comedy"
1,2,GoldenEye (1995),01-Jan-1995,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,"Action,Adventure,Thriller"
2,3,Four Rooms (1995),01-Jan-1995,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,Thriller
3,4,Get Shorty (1995),01-Jan-1995,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,"Action,Comedy,Drama"
4,5,Copycat (1995),01-Jan-1995,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,"Crime,Drama,Thriller"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Drama
1678,1679,B. Monkey (1998),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,"Romance,Thriller"
1679,1680,Sliding Doors (1998),01-Jan-1998,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,"Drama,Romance"
1680,1681,You So Crazy (1994),01-Jan-1994,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Comedy
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Drama

In [9]:
movies_df.head()

,item_id,title,release_date,video_Release_date,imdb_url,unknown,Action,Adventure,Animation,Children's,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,genre_label
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,"Animation,Children's,Comedy"
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,"Action,Adventure,Thriller"
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,Thriller
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,"Action,Comedy,Drama"
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,"Crime,Drama,Thriller"

In [10]:
movies_df=movies_df.drop(["video_Release_date","imdb_url"],axis=1)

In [11]:
movies_df=movies_df.drop(columns=genre_cols,axis=1)

In [12]:
movies_df.head()

   item_id              title release_date                  genre_label
0        1   Toy Story (1995)  01-Jan-1995  Animation,Children's,Comedy
1        2   GoldenEye (1995)  01-Jan-1995    Action,Adventure,Thriller
2        3  Four Rooms (1995)  01-Jan-1995                     Thriller
3        4  Get Shorty (1995)  01-Jan-1995          Action,Comedy,Drama
4        5     Copycat (1995)  01-Jan-1995         Crime,Drama,Thriller

In [13]:
movies_df["genre_label"] = movies_df["genre_label"].str.replace(",", "|")

In [14]:
interactions=pd.read_csv(
    "C:\\Users\\aksha\\OneDrive\\Desktop\\movies\\archive (3)\\ml-100k\\u.data",
    sep="\t",
    header=None,
    names=["user_id","item_id","rating","timestamp"]
)
interactions.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [15]:
users=pd.read_csv(
    "C:\\Users\\aksha\\OneDrive\\Desktop\\movies\\archive (3)\\ml-100k\\u.user",
    sep="|",
    names=["user_id","age","gender","occupatioin","zipcode"]
)
users.head()

   user_id  age gender occupatioin zipcode
0        1   24      M  technician   85711
1        2   53      F       other   94043
2        3   23      M      writer   32067
3        4   24      M  technician   43537
4        5   33      F       other   15213

In [16]:
merged_df=interactions.merge(users,on="user_id",how="left")

In [17]:
merged_df.head()

   user_id  item_id  rating  timestamp  age gender occupatioin zipcode
0      196      242       3  881250949   49      M      writer   55105
1      186      302       3  891717742   39      F   executive   00000
2       22      377       1  878887116   25      M      writer   40206
3      244       51       2  880606923   28      M  technician   80525
4      166      346       1  886397596   47      M    educator   55113

In [18]:
final_df=merged_df.merge(movies_df,on="item_id",how="left")

In [19]:
final_df.head()

,user_id,item_id,rating,timestamp,age,gender,occupatioin,zipcode,title,release_date,genre_label
0,196,242,3,881250949,49,M,writer,55105,Kolya (1996),24-Jan-1997,Comedy
1,186,302,3,891717742,39,F,executive,00000,L.A. Confidential (1997),01-Jan-1997,Crime|Film-Noir|Mystery|Thriller
2,22,377,1,878887116,25,M,writer,40206,Heavyweights (1994),01-Jan-1994,Children's|Comedy
3,244,51,2,880606923,28,M,technician,80525,Legends of the Fall (1994),01-Jan-1994,Drama|Romance|War|Western
4,166,346,1,886397596,47,M,educator,55113,Jackie Brown (1997),01-Jan-1997,Crime|Drama

In [20]:
final_df.drop(["timestamp","zipcode"],axis=1,inplace=True)

In [21]:
final_df.head(20)

,user_id,item_id,rating,age,gender,occupatioin,title,release_date,genre_label
0,196,242,3,49,M,writer,Kolya (1996),24-Jan-1997,Comedy
1,186,302,3,39,F,executive,L.A. Confidential (1997),01-Jan-1997,Crime|Film-Noir|Mystery|Thriller
2,22,377,1,25,M,writer,Heavyweights (1994),01-Jan-1994,Children's|Comedy
3,244,51,2,28,M,technician,Legends of the Fall (1994),01-Jan-1994,Drama|Romance|War|Western
4,166,346,1,47,M,educator,Jackie Brown (1997),01-Jan-1997,Crime|Drama
5,298,474,4,44,M,executive,Dr. Strangelove or: How I Learned to Stop Worr...,01-Jan-1963,Sci-Fi|War
6,115,265,2,31,M,engineer,"Hunt for Red October, The (1990)",01-Jan-1990,Action|Thriller
7,253,465,5,26,F,librarian,"Jungle Book, The (1994)",01-Jan-1994,Adventure|Children's|Romance
8,305,451,3,23,M,programmer,Grease (1978),01-Jan-1978,Comedy|Musical|Romance
9,6,86,3,42,M,executive,"Remains of the Day, The (1993)",01-Jan-1993,Drama
10,62,257,2,27,F,administrator,Men in Black (1997),04-Jul-1997,Action|Adventure|Comedy|Sci-Fi
11,286,1014,5,27,M,student,Romy and Michele's High School Reunion (1997),25-Apr-1997,Comedy
12,200,222,5,40,M,programmer,Star Trek: First Contact (1996),22-Nov-1996,Action|Adventure|Sci-Fi
13,210,40,3,39,M,engineer,"To Wong Foo, Thanks for Everything! Julie Newm...",01-Jan-1995,Comedy
14,224,29,3,31,F,educator,Batman Forever (1995),01-Jan-1995,Action|Adventure|Comedy|Crime
15,303,785,3,19,M,student,Only You (1994),01-Jan-1994,Comedy|Romance
16,122,387,5,32,F,writer,"Age of Innocence, The (1993)",01-Jan-1993,Drama
17,194,274,2,38,M,administrator,Sabrina (1995),01-Jan-1995,Comedy|Romance
18,291,1042,4,19,M,student,Just Cause (1995),01-Jan-1995,Mystery|Thriller
19,234,1184,2,60,M,retired,"Endless Summer 2, The (1994)",01-Jan-1994,Documentary

In [22]:
final_df.to_csv(r"C:\Users\aksha\OneDrive\Desktop\REBEM\movielens_final.csv")