In [61]:
import pandas as pd
tmdb_df=pd.read_csv(
    r"C:\Users\aksha\OneDrive\Desktop\REBEM\tmdb_movies.csv",
    )

In [62]:
movielens_df=pd.read_csv(
    r"C:\Users\aksha\OneDrive\Desktop\REBEM\movielens_data.csv",
    
    low_memory=False)

In [63]:
print(tmdb_df.dtypes)
print(tmdb_df.columns)
print(movielens_df.dtypes)
print(movielens_df.columns)

Unnamed: 0        int64
tmdb_id           int64
title            object
release_date     object
release_year      int64
language         object
genres           object
popularity      float64
vote_average    float64
vote_count        int64
overview         object
genre_labels     object
dtype: object
Index(['Unnamed: 0', 'tmdb_id', 'title', 'release_date', 'release_year',
       'language', 'genres', 'popularity', 'vote_average', 'vote_count',
       'overview', 'genre_labels'],
      dtype='object')
Unnamed: 0       int64
user_id          int64
item_id          int64
rating           int64
age              int64
gender          object
occupatioin     object
title           object
release_date    object
genre_label     object
dtype: object
Index(['Unnamed: 0', 'user_id', 'item_id', 'rating', 'age', 'gender',
       'occupatioin', 'title', 'release_date', 'genre_label'],
      dtype='object')

In [64]:
tmdb_df.columns

Index(['Unnamed: 0', 'tmdb_id', 'title', 'release_date', 'release_year',
       'language', 'genres', 'popularity', 'vote_average', 'vote_count',
       'overview', 'genre_labels'],
      dtype='object')

In [65]:
movielens_df.dtypes

Unnamed: 0       int64
user_id          int64
item_id          int64
rating           int64
age              int64
gender          object
occupatioin     object
title           object
release_date    object
genre_label     object
dtype: object

In [66]:
movielens_df.columns

Index(['Unnamed: 0', 'user_id', 'item_id', 'rating', 'age', 'gender',
       'occupatioin', 'title', 'release_date', 'genre_label'],
      dtype='object')

In [67]:
tmdb_df=tmdb_df.drop(columns=["Unnamed: 0"],axis=1)

In [68]:
movielens_df=movielens_df.drop(columns=["Unnamed: 0"],axis=1)

In [69]:
movielens_df=movielens_df.drop(columns=["release_date"],axis=1)
tmdb_df=tmdb_df.drop(columns=["release_date","genres"],axis=1)

In [70]:
tmdb_df.columns

Index(['tmdb_id', 'title', 'release_year', 'language', 'popularity',
       'vote_average', 'vote_count', 'overview', 'genre_labels'],
      dtype='object')

In [71]:
movielens_df.columns

Index(['user_id', 'item_id', 'rating', 'age', 'gender', 'occupatioin', 'title',
       'genre_label'],
      dtype='object')

In [72]:
tmdb_df.isnull().sum().sum()

94

In [73]:
movielens_df.isnull().sum().sum()

0

In [74]:
tmdb_df.isnull().sum()

tmdb_id          0
title            0
release_year     0
language         0
popularity       0
vote_average     0
vote_count       0
overview        94
genre_labels     0
dtype: int64

In [75]:
tmdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5039 entries, 0 to 5038
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5039 non-null   int64
 1   title         5039 non-null   object
 2   release_year  5039 non-null   int64
 3   language      5039 non-null   object
 4   popularity    5039 non-null   float64
 5   vote_average  5039 non-null   float64
 6   vote_count    5039 non-null   int64
 7   overview      4945 non-null   object
 8   genre_labels  5039 non-null   object
dtypes: float64(2), int64(3), object(4)
memory usage: 354.4+ KB

In [76]:
(tmdb_df == "").sum()

tmdb_id         0
title           0
release_year    0
language        0
popularity      0
vote_average    0
vote_count      0
overview        0
genre_labels    0
dtype: int64

In [77]:
(tmdb_df=="NaN").sum()

tmdb_id         0
title           0
release_year    0
language        0
popularity      0
vote_average    0
vote_count      0
overview        0
genre_labels    0
dtype: int64

In [78]:
tmdb_df.isnull().sum()

tmdb_id          0
title            0
release_year     0
language         0
popularity       0
vote_average     0
vote_count       0
overview        94
genre_labels     0
dtype: int64

In [79]:
tmdb_df["overview"]=tmdb_df["overview"].fillna("")

In [80]:
tmdb_df.isnull().sum()

tmdb_id         0
title           0
release_year    0
language        0
popularity      0
vote_average    0
vote_count      0
overview        0
genre_labels    0
dtype: int64

In [81]:
tmdb_df.isna().sum()

tmdb_id         0
title           0
release_year    0
language        0
popularity      0
vote_average    0
vote_count      0
overview        0
genre_labels    0
dtype: int64

In [82]:
movielens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      100000 non-null  int64
 1   item_id      100000 non-null  int64
 2   rating       100000 non-null  int64
 3   age          100000 non-null  int64
 4   gender       100000 non-null  object
 5   occupatioin  100000 non-null  object
 6   title        100000 non-null  object
 7   genre_label  100000 non-null  object
dtypes: int64(4), object(4)
memory usage: 6.1+ MB

In [83]:
type(tmdb_df["genre_labels"].iloc[0])

str

In [84]:
type(movielens_df["genre_label"].iloc[0])

str

In [85]:
movielens_df["rating"].unique()

array([3, 1, 2, 4, 5], dtype=int64)

In [86]:
movielens_df["age"].unique()

array([49, 39, 25, 28, 47, 44, 31, 26, 23, 42, 27, 40, 19, 32, 38, 60, 37,
       29, 21, 24, 51, 43, 57, 53, 33, 20, 48, 30, 35, 46, 50, 16, 36, 22,
       54, 55, 34, 45, 18, 15, 13, 41, 17, 59, 56, 61, 14, 52, 65,  7, 11,
       62, 66, 68, 63, 64, 10, 73, 58, 69, 70], dtype=int64)

In [87]:
movielens_df["gender"]=movielens_df["gender"].astype("category")

In [88]:
movielens_df["occupation"]=movielens_df["occupatioin"].astype("category")

In [89]:
movielens_df.head()

,user_id,item_id,rating,age,gender,occupatioin,title,genre_label,occupation
0,196,242,3,49,M,writer,Kolya (1996),['Comedy'],writer
1,186,302,3,39,F,executive,L.A. Confidential (1997),"['Thriller', 'Mystery', 'Film-Noir', 'Crime']",executive
2,22,377,1,25,M,writer,Heavyweights (1994),"['Family', 'Comedy']",writer
3,244,51,2,28,M,technician,Legends of the Fall (1994),"['War', 'Drama', 'Western', 'Romance']",technician
4,166,346,1,47,M,educator,Jackie Brown (1997),"['Drama', 'Crime']",educator

In [90]:
movielens_df=movielens_df.drop(columns=["occupatioin"],axis=1)

In [91]:
movielens_df.head()

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3,49,M,Kolya (1996),['Comedy'],writer
1,186,302,3,39,F,L.A. Confidential (1997),"['Thriller', 'Mystery', 'Film-Noir', 'Crime']",executive
2,22,377,1,25,M,Heavyweights (1994),"['Family', 'Comedy']",writer
3,244,51,2,28,M,Legends of the Fall (1994),"['War', 'Drama', 'Western', 'Romance']",technician
4,166,346,1,47,M,Jackie Brown (1997),"['Drama', 'Crime']",educator

In [92]:
movielens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      100000 non-null  int64
 1   item_id      100000 non-null  int64
 2   rating       100000 non-null  int64
 3   age          100000 non-null  int64
 4   gender       100000 non-null  category
 5   title        100000 non-null  object
 6   genre_label  100000 non-null  object
 7   occupation   100000 non-null  category
dtypes: category(2), int64(4), object(2)
memory usage: 4.8+ MB

In [93]:
tmdb_df.head()

,tmdb_id,title,release_year,language,popularity,vote_average,vote_count,overview,genre_labels
0,98,Gladiator,2000,en,21.0347,8.221,20485,"After the death of Emperor Marcus Aurelius, hi...","['Adventure', 'Drama', 'Action']"
1,111646,Biyaheng Langit,2000,en,17.0227,2.000,2,"Biyaheng Langit tells the story of Bea, a youn...","['Drama', 'Action', 'Romance']"
2,107,Snatch,2000,en,14.6372,7.816,9731,"Unscrupulous boxing promoters, violent bookies...","['Comedy', 'Crime']"
3,11688,The Emperor's New Groove,2000,en,14.7474,7.558,7162,Emperor Kuzco is turned into a llama by his ex...,"['Fantasy', 'Adventure', 'Family', 'Comedy', '..."
4,1359,American Psycho,2000,en,14.5561,7.406,11963,A wealthy New York investment banking executiv...,"['Thriller', 'Drama', 'Crime']"

In [95]:
type(tmdb_df["genre_labels"].iloc[0])

str

In [97]:
type(movielens_df["genre_label"].iloc[0])

str

In [100]:
tmdb_df["genre_labels"].unique()[:10]

array(["['Adventure', 'Drama', 'Action']",
       "['Drama', 'Action', 'Romance']", "['Comedy', 'Crime']",
       "['Fantasy', 'Adventure', 'Family', 'Comedy', 'Animation']",
       "['Thriller', 'Drama', 'Crime']", "['Adventure', 'Drama']",
       "['Thriller', 'Mystery']", "['Fantasy', 'Family', 'Comedy']",
       "['Comedy']", "['Adventure', 'Thriller', 'Action']"], dtype=object)

In [102]:
tmdb_df[tmdb_df["genre_labels"].str.contains(r"^\[", na=False) == False].head()

,tmdb_id,title,release_year,language,popularity,vote_average,vote_count,overview,genre_labels
1042,330751,Kouravudu,2000,te,2.9706,0.0,0,Kouravudu is a 2000 Telugu movie starring Nage...,unknown
1043,435916,Bagunnara?,2000,te,2.7299,10.0,1,A young woman meets a man and falls in love wi...,unknown
1047,137248,Chiru Navvuto,2000,te,0.5088,7.7,3,Chirunavvutho is the story about Venu (Venu) w...,unknown
1051,137466,Nuvvu Vastavani,2000,te,0.5376,6.2,5,The movie starts with Chinni (Nagarjuna) revea...,unknown
1068,80950,Chitram,2000,te,0.3173,5.5,2,Janaki comes to India from US and joins a coll...,unknown

In [109]:
import ast
def eval(x):
    if isinstance(x,str):
        x=x.strip()
        if x.startswith("[") and x.endswith("]"):
            return ast.literal_eval(x)
        return[x]
    return x

In [110]:
tmdb_df["genre_labels"]=tmdb_df["genre_labels"].apply(eval)

In [105]:
import ast
movielens_df["genre_label"]=movielens_df["genre_label"].apply(
    lambda x:ast.literal_eval(x) if isinstance(x,str) else x)

In [111]:
type(tmdb_df["genre_labels"].iloc[0])

list

In [113]:
type(movielens_df["genre_label"].iloc[0])

list

In [114]:
movielens_df["rating"]=movielens_df["rating"].astype(float)

In [115]:
movielens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      100000 non-null  int64
 1   item_id      100000 non-null  int64
 2   rating       100000 non-null  float64
 3   age          100000 non-null  int64
 4   gender       100000 non-null  category
 5   title        100000 non-null  object
 6   genre_label  100000 non-null  object
 7   occupation   100000 non-null  category
dtypes: category(2), float64(1), int64(3), object(2)
memory usage: 4.8+ MB

In [116]:
movielens_df.head()

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,M,Kolya (1996),[Comedy],writer
1,186,302,3.0,39,F,L.A. Confidential (1997),"[Thriller, Mystery, Film-Noir, Crime]",executive
2,22,377,1.0,25,M,Heavyweights (1994),"[Family, Comedy]",writer
3,244,51,2.0,28,M,Legends of the Fall (1994),"[War, Drama, Western, Romance]",technician
4,166,346,1.0,47,M,Jackie Brown (1997),"[Drama, Crime]",educator

In [118]:
movielens_df.to_pickle(r"C:\Users\aksha\OneDrive\Desktop\REBEM\movielens_for_scaling.pkl")

In [119]:
tmdb_df.to_pickle(r"C:\Users\aksha\OneDrive\Desktop\REBEM\tmdb_for_scaling.pkl")