In [1]:
import pandas as pd
df=pd.read_pickle(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\processed\movielens_for_collab.pkl")
df1=pd.read_pickle(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\processed\tmdb_for_content.pkl")

In [2]:
df.info()
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      100000 non-null  int64
 1   item_id      100000 non-null  int64
 2   rating       100000 non-null  float64
 3   age          100000 non-null  int64
 4   gender       100000 non-null  category
 5   title        100000 non-null  object
 6   genre_label  100000 non-null  object
 7   occupation   100000 non-null  category
dtypes: category(2), float64(1), int64(3), object(2)
memory usage: 4.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tmdb_id            5175 non-null   int64
 1   title              5175 non-null   object
 2   language           5175 non-null   object
 3   genres             5175 non-null   object
 4   popularity         5175 non-null   float64
 5   vote_average       5175 non-null   float64
 6   vote_count         5175 non-null   int32
 7   overview           5175 non-null   object
 8   cast               5175 non-null   object
 9   director           5175 non-null   object
 10  keywords           5175 non-null   object
 11  release_year       5175 non-null   int32
 12  combined_features  5175 non-null   object
dtypes: float64(2), int32(2), int64(1), object(8)
memory usage: 485.3+ KB

In [4]:
df.head()

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,1,kolya (1996),comedy,writer
1,186,302,3.0,39,0,l.a. confidential (1997),thriller mystery noir crime,executive
2,22,377,1.0,25,1,heavyweights (1994),comedy children,writer
3,244,51,2.0,28,1,legends of the fall (1994),western war drama romance,technician
4,166,346,1.0,47,1,jackie brown (1997),drama crime,educator

In [5]:
movielens_genres=set()
for genres in df["genre_label"]:
    for g in genres.split():
        movielens_genres.add(g.strip())

print(sorted(movielens_genres))

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'horror', 'music', 'mystery', 'noir', 'romance', 'sci-fi', 'thriller', 'war', 'western']

In [6]:
tmdb_genres=set()
for genres in df1["genres"]:
    for g in genres.split():
        tmdb_genres.add(g.strip())

print(sorted(tmdb_genres))

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'history', 'horror', 'music', 'mystery', 'romance', 'sci-fi', 'thriller', 'war', 'western']

In [7]:
import re 
def split_title(title):
    match=re.search(r"\((\d{4})\)",title)
    if match:
        year=int(match.group(1))
    else:
        year=None

    clean_title=re.sub(r"\(\d{4}\)","",title).strip().lower()
    return clean_title,year

In [8]:
df[["clean_title","year"]]=df["title"].apply(lambda x:pd.Series(split_title(x)))

In [9]:
df.head()

,user_id,item_id,rating,age,gender,title,genre_label,occupation,clean_title,year
0,196,242,3.0,49,1,kolya (1996),comedy,writer,kolya,1996.0
1,186,302,3.0,39,0,l.a. confidential (1997),thriller mystery noir crime,executive,l.a. confidential,1997.0
2,22,377,1.0,25,1,heavyweights (1994),comedy children,writer,heavyweights,1994.0
3,244,51,2.0,28,1,legends of the fall (1994),western war drama romance,technician,legends of the fall,1994.0
4,166,346,1.0,47,1,jackie brown (1997),drama crime,educator,jackie brown,1997.0

In [10]:
df["year"]=df["year"].fillna(0).astype(int)

In [11]:
df["year"].isnull().sum()

0

In [12]:
df["clean_title"].isnull().sum()

0

In [13]:
df.head()

,user_id,item_id,rating,age,gender,title,genre_label,occupation,clean_title,year
0,196,242,3.0,49,1,kolya (1996),comedy,writer,kolya,1996
1,186,302,3.0,39,0,l.a. confidential (1997),thriller mystery noir crime,executive,l.a. confidential,1997
2,22,377,1.0,25,1,heavyweights (1994),comedy children,writer,heavyweights,1994
3,244,51,2.0,28,1,legends of the fall (1994),western war drama romance,technician,legends of the fall,1994
4,166,346,1.0,47,1,jackie brown (1997),drama crime,educator,jackie brown,1997

In [14]:
df=df.drop("title",axis=1)

In [15]:
df.head()

,user_id,item_id,rating,age,gender,genre_label,occupation,clean_title,year
0,196,242,3.0,49,1,comedy,writer,kolya,1996
1,186,302,3.0,39,0,thriller mystery noir crime,executive,l.a. confidential,1997
2,22,377,1.0,25,1,comedy children,writer,heavyweights,1994
3,244,51,2.0,28,1,western war drama romance,technician,legends of the fall,1994
4,166,346,1.0,47,1,drama crime,educator,jackie brown,1997

In [16]:
df.shape

(100000, 9)

In [17]:
user_item_matrix=df.pivot_table(index="user_id",columns="clean_title",values="rating")

In [18]:
print(user_item_matrix)

clean_title  'til there was you  1-900  101 dalmatians  12 angry men  187  \
user_id
1                           NaN    NaN             2.0           5.0  NaN
2                           NaN    NaN             NaN           NaN  NaN
3                           NaN    NaN             NaN           NaN  2.0
4                           NaN    NaN             NaN           NaN  NaN
5                           NaN    NaN             2.0           NaN  NaN
...                         ...    ...             ...           ...  ...
939                         NaN    NaN             NaN           NaN  NaN
940                         NaN    NaN             NaN           NaN  NaN
941                         NaN    NaN             NaN           NaN  NaN
942                         NaN    NaN             NaN           NaN  NaN
943                         NaN    NaN             NaN           NaN  NaN

clean_title  2 days in the valley  20,000 leagues under the sea  \
user_id
1                             NaN                           3.0
2                             NaN                           NaN
3                             NaN                           NaN
4                             NaN                           NaN
5                             NaN                           NaN
...                           ...                           ...
939                           NaN                           NaN
940                           NaN                           NaN
941                           NaN                           NaN
942                           NaN                           NaN
943                           2.0                           NaN

clean_title  2001: a space odyssey  3 ninjas: high noon at mega mountain  \
user_id
1                              4.0                                   NaN
2                              NaN                                   1.0
3                              NaN                                   NaN
4                              NaN                                   NaN
5                              4.0                                   NaN
...                            ...                                   ...
939                            NaN                                   NaN
940                            NaN                                   NaN
941                            NaN                                   NaN
942                            3.0                                   NaN
943                            NaN                                   NaN

clean_title  39 steps, the  ...  wyatt earp  yankee zulu  year of the horse  \
user_id                     ...
1                      NaN  ...         NaN          NaN                NaN
2                      NaN  ...         NaN          NaN                NaN
3                      NaN  ...         NaN          NaN                NaN
4                      NaN  ...         NaN          NaN                NaN
5                      NaN  ...         NaN          NaN                NaN
...                    ...  ...         ...          ...                ...
939                    NaN  ...         NaN          NaN                NaN
940                    NaN  ...         NaN          NaN                NaN
941                    NaN  ...         NaN          NaN                NaN
942                    3.0  ...         NaN          NaN                NaN
943                    NaN  ...         1.0          NaN                NaN

clean_title  you so crazy  young frankenstein  young guns  young guns ii  \
user_id
1                     NaN                 5.0         3.0            NaN
2                     NaN                 NaN         NaN            NaN
3                     NaN                 NaN         NaN            NaN
4                     NaN                 NaN         NaN            NaN
5                     NaN                 4.0         NaN            NaN
...                   ...                 ...         ...            ...
939                   NaN                 NaN         NaN            NaN
940                   NaN                 NaN         NaN            NaN
941                   NaN                 NaN         NaN            NaN
942                   NaN                 NaN         NaN            NaN
943                   NaN                 NaN         4.0            3.0

clean_title  young poisoner's handbook, the  zeus and roxanne  \
user_id
1                                       NaN               NaN
2                                       NaN               NaN
3                                       NaN               NaN
4                                       NaN               NaN
5                                       NaN               NaN
...                                     ...               ...
939                                     NaN               NaN
940                                     NaN               NaN
941                                     NaN               NaN
942                                     NaN               NaN
943                                     NaN               NaN

clean_title  á köldum klaka (cold fever)
user_id
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
5                                    NaN
...                                  ...
939                                  NaN
940                                  NaN
941                                  NaN
942                                  NaN
943                                  NaN

[943 rows x 1659 columns]

In [19]:
user_item_matrix.fillna(0)

clean_title,'til there was you,1-900,101 dalmatians,12 angry men,187,2 days in the valley,"20,000 leagues under the sea",2001: a space odyssey,3 ninjas: high noon at mega mountain,"39 steps, the",...,wyatt earp,yankee zulu,year of the horse,you so crazy,young frankenstein,young guns,young guns ii,"young poisoner's handbook, the",zeus and roxanne,á köldum klaka (cold fever)
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,2.0,5.0,0.0,0.0,3.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,4.0,3.0,0.0,0.0,0.0

In [20]:
df["item_id"].nunique()

1682

In [21]:
df["clean_title"].nunique()

1659

In [22]:
df.groupby(["clean_title","year"]).nunique()

,,user_id,item_id,rating,age,gender,genre_label,occupation
clean_title,year,,,,,,,
'til there was you,1997,9,1,4,7,2,1,6
1-900,1994,5,1,3,5,2,1,4
101 dalmatians,1996,109,1,5,40,2,1,19
12 angry men,1957,125,1,4,41,2,1,18
187,1997,41,1,5,26,2,1,16
...,...,...,...,...,...,...,...,...
young guns,1988,101,1,5,28,2,1,17
young guns ii,1990,44,1,5,17,2,1,12
"young poisoner's handbook, the",1995,41,1,5,25,2,1,14
zeus and roxanne,1997,6,1,3,5,2,1,5
á köldum klaka (cold fever),1994,1,1,1,1,1,1,1

In [23]:
df.groupby(["clean_title","year"]).nunique()

,,user_id,item_id,rating,age,gender,genre_label,occupation
clean_title,year,,,,,,,
'til there was you,1997,9,1,4,7,2,1,6
1-900,1994,5,1,3,5,2,1,4
101 dalmatians,1996,109,1,5,40,2,1,19
12 angry men,1957,125,1,4,41,2,1,18
187,1997,41,1,5,26,2,1,16
...,...,...,...,...,...,...,...,...
young guns,1988,101,1,5,28,2,1,17
young guns ii,1990,44,1,5,17,2,1,12
"young poisoner's handbook, the",1995,41,1,5,25,2,1,14
zeus and roxanne,1997,6,1,3,5,2,1,5
á köldum klaka (cold fever),1994,1,1,1,1,1,1,1

In [24]:
df.groupby("clean_title")["item_id"].nunique().sort_values(ascending=False).head(10)

clean_title
that darn cat!            3
ulee's gold               2
hugo pool                 2
cape fear                 2
shall we dance?           2
chairman of the board     2
butcher boy, the          2
scarlet letter, the       2
chasing amy               2
substance of fire, the    2
Name: item_id, dtype: int64

In [25]:
title_id=df.groupby("clean_title")["item_id"].first()

In [26]:
print(title_id)

clean_title
'til there was you                1300
1-900                             1353
101 dalmatians                     225
12 angry men                       178
187                                330
                                  ...
young guns                         232
young guns ii                     1188
young poisoner's handbook, the     547
zeus and roxanne                  1164
á köldum klaka (cold fever)       1633
Name: item_id, Length: 1659, dtype: int64

In [27]:
df["item_id"]=df["clean_title"].map(title_id)

In [28]:
df.groupby("clean_title")["item_id"].nunique().sort_values(ascending=False).head()

clean_title
'til there was you           1
one night stand              1
outbreak                     1
out to sea                   1
other voices, other rooms    1
Name: item_id, dtype: int64

In [29]:
df["item_id"].nunique()

1659

In [30]:
df["clean_title"].nunique()

1659

In [31]:
df.groupby(["clean_title","year"]).nunique()

,,user_id,item_id,rating,age,gender,genre_label,occupation
clean_title,year,,,,,,,
'til there was you,1997,9,1,4,7,2,1,6
1-900,1994,5,1,3,5,2,1,4
101 dalmatians,1996,109,1,5,40,2,1,19
12 angry men,1957,125,1,4,41,2,1,18
187,1997,41,1,5,26,2,1,16
...,...,...,...,...,...,...,...,...
young guns,1988,101,1,5,28,2,1,17
young guns ii,1990,44,1,5,17,2,1,12
"young poisoner's handbook, the",1995,41,1,5,25,2,1,14
zeus and roxanne,1997,6,1,3,5,2,1,5
á köldum klaka (cold fever),1994,1,1,1,1,1,1,1

In [32]:
df.groupby("clean_title")["year"].nunique().sort_values(ascending=False).head()

clean_title
cape fear              2
sabrina                2
scarlet letter, the    2
that darn cat!         2
shall we dance?        2
Name: year, dtype: int64

In [33]:
df["movie_id"]=df["clean_title"]+"-"+df["year"].astype(str)

In [34]:
title_id=df.groupby("movie_id")["item_id"].first()

In [35]:
df["item_id"]=df["movie_id"].map(title_id)

In [36]:
df["movie_id"].nunique()

1664

In [37]:
df["item_id"].nunique()

1659

In [38]:
df.head()

,user_id,item_id,rating,age,gender,genre_label,occupation,clean_title,year,movie_id
0,196,242,3.0,49,1,comedy,writer,kolya,1996,kolya-1996
1,186,302,3.0,39,0,thriller mystery noir crime,executive,l.a. confidential,1997,l.a. confidential-1997
2,22,377,1.0,25,1,comedy children,writer,heavyweights,1994,heavyweights-1994
3,244,51,2.0,28,1,western war drama romance,technician,legends of the fall,1994,legends of the fall-1994
4,166,346,1.0,47,1,drama crime,educator,jackie brown,1997,jackie brown-1997

In [39]:
(df["genre_label"].isna() | (df["genre_label"]=="")).sum()

10

In [40]:
df[(df["genre_label"]=="")]

,user_id,item_id,rating,age,gender,genre_label,occupation,clean_title,year,movie_id
2172,130,267,5.0,20,1,,none,unknown,0,unknown-0
3781,5,267,4.0,33,0,,other,unknown,0,unknown-0
7245,268,267,3.0,24,1,,engineer,unknown,0,unknown-0
8567,181,1373,1.0,26,1,,executive,good morning,1971,good morning-1971
12475,297,267,3.0,29,0,,educator,unknown,0,unknown-0
14756,319,267,4.0,38,1,,programmer,unknown,0,unknown-0
15292,1,267,4.0,24,1,,technician,unknown,0,unknown-0
49295,532,267,3.0,20,1,,student,unknown,0,unknown-0
93523,833,267,1.0,34,1,,writer,unknown,0,unknown-0
99723,422,267,4.0,26,1,,entertainment,unknown,0,unknown-0

In [41]:
df=df[df["genre_label"].notna() & (df["genre_label"].str.strip()!="")]

In [42]:
df[(df["genre_label"]=="")]

Empty DataFrame
Columns: [user_id, item_id, rating, age, gender, genre_label, occupation, clean_title, year, movie_id]
Index: []

In [43]:
df=df.reset_index(drop=True)

In [44]:
df.head()

,user_id,item_id,rating,age,gender,genre_label,occupation,clean_title,year,movie_id
0,196,242,3.0,49,1,comedy,writer,kolya,1996,kolya-1996
1,186,302,3.0,39,0,thriller mystery noir crime,executive,l.a. confidential,1997,l.a. confidential-1997
2,22,377,1.0,25,1,comedy children,writer,heavyweights,1994,heavyweights-1994
3,244,51,2.0,28,1,western war drama romance,technician,legends of the fall,1994,legends of the fall-1994
4,166,346,1.0,47,1,drama crime,educator,jackie brown,1997,jackie brown-1997

In [45]:
df.isnull().sum()

user_id        0
item_id        0
rating         0
age            0
gender         0
genre_label    0
occupation     0
clean_title    0
year           0
movie_id       0
dtype: int64

In [46]:
df["rating"].nunique()

5

In [47]:
df["movie_id"].nunique()

1662

In [48]:
df["item_id"].nunique()

1657

In [49]:
df["clean_title"].nunique()

1657

In [50]:
df.groupby("clean_title")["year"].nunique().sort_values(ascending=False).head(8)

clean_title
shall we dance?             2
that darn cat!              2
sabrina                     2
scarlet letter, the         2
cape fear                   2
omen, the                   1
open season                 1
old man and the sea, the    1
Name: year, dtype: int64

In [51]:
df=df.drop(["movie_id"],axis=1)

In [52]:
year1=df.groupby("clean_title")["year"].max()

In [53]:
print(year1)

clean_title
'til there was you                1997
1-900                             1994
101 dalmatians                    1996
12 angry men                      1957
187                               1997
                                  ...
young guns                        1988
young guns ii                     1990
young poisoner's handbook, the    1995
zeus and roxanne                  1997
á köldum klaka (cold fever)       1994
Name: year, Length: 1657, dtype: int32

In [54]:
df["year"]=df["clean_title"].map(year1)

In [55]:
df.groupby("clean_title")["year"].nunique().sort_values(ascending=False).head()

clean_title
'til there was you           1
one night stand              1
outbreak                     1
out to sea                   1
other voices, other rooms    1
Name: year, dtype: int64

In [56]:
df.groupby(["clean_title","year"]).nunique()

,,user_id,item_id,rating,age,gender,genre_label,occupation
clean_title,year,,,,,,,
'til there was you,1997,9,1,4,7,2,1,6
1-900,1994,5,1,3,5,2,1,4
101 dalmatians,1996,109,1,5,40,2,1,19
12 angry men,1957,125,1,4,41,2,1,18
187,1997,41,1,5,26,2,1,16
...,...,...,...,...,...,...,...,...
young guns,1988,101,1,5,28,2,1,17
young guns ii,1990,44,1,5,17,2,1,12
"young poisoner's handbook, the",1995,41,1,5,25,2,1,14
zeus and roxanne,1997,6,1,3,5,2,1,5
á köldum klaka (cold fever),1994,1,1,1,1,1,1,1

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99990 entries, 0 to 99989
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      99990 non-null  int64
 1   item_id      99990 non-null  int64
 2   rating       99990 non-null  float64
 3   age          99990 non-null  int64
 4   gender       99990 non-null  category
 5   genre_label  99990 non-null  object
 6   occupation   99990 non-null  category
 7   clean_title  99990 non-null  object
 8   year         99990 non-null  int32
dtypes: category(2), float64(1), int32(1), int64(3), object(2)
memory usage: 5.1+ MB

In [58]:
df.head()

,user_id,item_id,rating,age,gender,genre_label,occupation,clean_title,year
0,196,242,3.0,49,1,comedy,writer,kolya,1996
1,186,302,3.0,39,0,thriller mystery noir crime,executive,l.a. confidential,1997
2,22,377,1.0,25,1,comedy children,writer,heavyweights,1994
3,244,51,2.0,28,1,western war drama romance,technician,legends of the fall,1994
4,166,346,1.0,47,1,drama crime,educator,jackie brown,1997

In [59]:
df.tail()

,user_id,item_id,rating,age,gender,genre_label,occupation,clean_title,year
99985,880,476,3.0,13,1,comedy,student,"first wives club, the",1996
99986,716,204,5.0,36,0,comedy sci-fi,administrator,back to the future,1985
99987,276,1090,1.0,21,1,thriller,student,sliver,1993
99988,13,225,2.0,47,1,comedy children,educator,101 dalmatians,1996
99989,12,203,3.0,28,0,western,other,unforgiven,1992

In [60]:
print(df["item_id"].nunique())
print(df["clean_title"].nunique())
print(df.groupby(["clean_title","year"]).nunique())

1657
1657
                                     user_id  item_id  rating  age  gender  \
clean_title                    year
'til there was you             1997        9        1       4    7       2
1-900                          1994        5        1       3    5       2
101 dalmatians                 1996      109        1       5   40       2
12 angry men                   1957      125        1       4   41       2
187                            1997       41        1       5   26       2
...                                      ...      ...     ...  ...     ...
young guns                     1988      101        1       5   28       2
young guns ii                  1990       44        1       5   17       2
young poisoner's handbook, the 1995       41        1       5   25       2
zeus and roxanne               1997        6        1       3    5       2
á köldum klaka (cold fever)    1994        1        1       1    1       1

                                     genre_label  occupation
clean_title                    year
'til there was you             1997            1           6
1-900                          1994            1           4
101 dalmatians                 1996            1          19
12 angry men                   1957            1          18
187                            1997            1          16
...                                          ...         ...
young guns                     1988            1          17
young guns ii                  1990            1          12
young poisoner's handbook, the 1995            1          14
zeus and roxanne               1997            1           5
á köldum klaka (cold fever)    1994            1           1

[1657 rows x 7 columns]

In [61]:
df.to_pickle(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\processed\movielens_for_collaborative.pkl")