In [1]:
import pandas as pd
df_te=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_te.csv")
df_en=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_en.csv")
df_hi=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_hi.csv")
df_kn=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_kn.csv")
df_ta=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_ta.csv")
df_en_2026=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_2026_en.csv")
df_te_2026=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_2026_te.csv")
df_hi_2026=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_2026_hi.csv")
df_kn_2026=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_2026_kn.csv")
df_ta_2026=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb_movies_2026_ta.csv")

In [2]:
tmdb_merged_df=pd.concat(
    [df_en,df_te,df_hi,df_ta,df_kn,df_en_2026,df_te_2026,df_hi_2026,df_kn_2026,df_ta_2026],ignore_index=True)

In [3]:
tmdb_merged_df.head()

,tmdb_id,title,release_date,release_year,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords
0,4247,Scary Movie,2000-07-07,2000.0,en,[35],22.2560,6.388,7623.0,A familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...
1,98,Gladiator,2000-05-04,2000.0,en,"[28, 18, 12]",18.2146,8.223,20647.0,"After the death of Emperor Marcus Aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir..."
2,4234,Scream 3,2000-02-04,2000.0,en,"[27, 9648]",11.5470,6.007,3982.0,As bodies begin dropping around the Hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...
3,11688,The Emperor's New Groove,2000-12-15,2000.0,en,"[12, 16, 35, 10751, 14]",11.2891,7.557,7218.0,Emperor Kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...
4,77,Memento,2000-10-11,2000.0,en,"[9648, 53]",11.6323,8.176,16025.0,Leonard Shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...

In [4]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5175 non-null   int64
 1   title         5175 non-null   object
 2   release_date  5175 non-null   object
 3   release_year  5075 non-null   float64
 4   language      5175 non-null   object
 5   genres        5175 non-null   object
 6   popularity    5175 non-null   float64
 7   vote_average  5175 non-null   float64
 8   vote_count    5075 non-null   float64
 9   overview      5091 non-null   object
 10  cast          5127 non-null   object
 11  director      5049 non-null   object
 12  keywords      2492 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 525.7+ KB

In [5]:
tmdb_merged_df=tmdb_merged_df.drop_duplicates(
    subset=["tmdb_id","language"]
)

In [6]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5175 non-null   int64
 1   title         5175 non-null   object
 2   release_date  5175 non-null   object
 3   release_year  5075 non-null   float64
 4   language      5175 non-null   object
 5   genres        5175 non-null   object
 6   popularity    5175 non-null   float64
 7   vote_average  5175 non-null   float64
 8   vote_count    5075 non-null   float64
 9   overview      5091 non-null   object
 10  cast          5127 non-null   object
 11  director      5049 non-null   object
 12  keywords      2492 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 525.7+ KB

In [7]:
tmdb_merged_df.duplicated(subset=["tmdb_id","language"]).sum()

0

In [8]:
tmdb_merged_df.isnull().sum()

tmdb_id            0
title              0
release_date       0
release_year     100
language           0
genres             0
popularity         0
vote_average       0
vote_count       100
overview          84
cast              48
director         126
keywords        2683
dtype: int64

In [9]:
tmdb_merged_df["release_date"]=pd.to_datetime(tmdb_merged_df["release_date"],errors="coerce")

In [10]:
tmdb_merged_df["release_yearr"]=tmdb_merged_df["release_date"].dt.year

In [11]:
tmdb_merged_df.head()

,tmdb_id,title,release_date,release_year,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords,release_yearr
0,4247,Scary Movie,2000-07-07,2000.0,en,[35],22.2560,6.388,7623.0,A familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...,2000
1,98,Gladiator,2000-05-04,2000.0,en,"[28, 18, 12]",18.2146,8.223,20647.0,"After the death of Emperor Marcus Aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir...",2000
2,4234,Scream 3,2000-02-04,2000.0,en,"[27, 9648]",11.5470,6.007,3982.0,As bodies begin dropping around the Hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...,2000
3,11688,The Emperor's New Groove,2000-12-15,2000.0,en,"[12, 16, 35, 10751, 14]",11.2891,7.557,7218.0,Emperor Kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...,2000
4,77,Memento,2000-10-11,2000.0,en,"[9648, 53]",11.6323,8.176,16025.0,Leonard Shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...,2000

In [12]:
tmdb_merged_df.isnull().sum()

tmdb_id             0
title               0
release_date        0
release_year      100
language            0
genres              0
popularity          0
vote_average        0
vote_count        100
overview           84
cast               48
director          126
keywords         2683
release_yearr       0
dtype: int64

In [13]:
tmdb_merged_df=tmdb_merged_df.drop(columns=["release_year"])

In [14]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tmdb_id        5175 non-null   int64
 1   title          5175 non-null   object
 2   release_date   5175 non-null   datetime64[ns]
 3   language       5175 non-null   object
 4   genres         5175 non-null   object
 5   popularity     5175 non-null   float64
 6   vote_average   5175 non-null   float64
 7   vote_count     5075 non-null   float64
 8   overview       5091 non-null   object
 9   cast           5127 non-null   object
 10  director       5049 non-null   object
 11  keywords       2492 non-null   object
 12  release_yearr  5175 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(7)
memory usage: 505.5+ KB

In [15]:
tmdb_merged_df["release_year"]=tmdb_merged_df["release_yearr"]

In [16]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tmdb_id        5175 non-null   int64
 1   title          5175 non-null   object
 2   release_date   5175 non-null   datetime64[ns]
 3   language       5175 non-null   object
 4   genres         5175 non-null   object
 5   popularity     5175 non-null   float64
 6   vote_average   5175 non-null   float64
 7   vote_count     5075 non-null   float64
 8   overview       5091 non-null   object
 9   cast           5127 non-null   object
 10  director       5049 non-null   object
 11  keywords       2492 non-null   object
 12  release_yearr  5175 non-null   int32
 13  release_year   5175 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(7)
memory usage: 525.7+ KB

In [17]:
tmdb_merged_df=tmdb_merged_df.drop(columns=["release_yearr","release_date"])

In [18]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5175 non-null   int64
 1   title         5175 non-null   object
 2   language      5175 non-null   object
 3   genres        5175 non-null   object
 4   popularity    5175 non-null   float64
 5   vote_average  5175 non-null   float64
 6   vote_count    5075 non-null   float64
 7   overview      5091 non-null   object
 8   cast          5127 non-null   object
 9   director      5049 non-null   object
 10  keywords      2492 non-null   object
 11  release_year  5175 non-null   int32
dtypes: float64(3), int32(1), int64(1), object(7)
memory usage: 465.1+ KB

In [19]:
tmdb_merged_df["vote_count"]=tmdb_merged_df["vote_count"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [20]:
import numpy as np
tmdb_merged_df["vote_count"]=tmdb_merged_df["vote_count"].replace([np.inf,-np.inf],np.nan)

In [21]:
tmdb_merged_df["vote_count"]=tmdb_merged_df["vote_count"].fillna(0)

In [22]:
tmdb_merged_df["vote_count"].isnull().sum()

0

In [23]:
tmdb_merged_df["vote_count"]=tmdb_merged_df["vote_count"].astype(int)

In [24]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5175 non-null   int64
 1   title         5175 non-null   object
 2   language      5175 non-null   object
 3   genres        5175 non-null   object
 4   popularity    5175 non-null   float64
 5   vote_average  5175 non-null   float64
 6   vote_count    5175 non-null   int32
 7   overview      5091 non-null   object
 8   cast          5127 non-null   object
 9   director      5049 non-null   object
 10  keywords      2492 non-null   object
 11  release_year  5175 non-null   int32
dtypes: float64(2), int32(2), int64(1), object(7)
memory usage: 444.9+ KB

In [25]:
tmdb_merged_df["overview"]=tmdb_merged_df["overview"].fillna("")
tmdb_merged_df["cast"]=tmdb_merged_df["cast"].fillna("")
tmdb_merged_df["director"]=tmdb_merged_df["director"].fillna("")
tmdb_merged_df["keywords"]=tmdb_merged_df["keywords"].fillna("")

In [26]:
tmdb_merged_df.isnull().sum()

tmdb_id         0
title           0
language        0
genres          0
popularity      0
vote_average    0
vote_count      0
overview        0
cast            0
director        0
keywords        0
release_year    0
dtype: int64

In [27]:
tmdb_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5175 non-null   int64
 1   title         5175 non-null   object
 2   language      5175 non-null   object
 3   genres        5175 non-null   object
 4   popularity    5175 non-null   float64
 5   vote_average  5175 non-null   float64
 6   vote_count    5175 non-null   int32
 7   overview      5175 non-null   object
 8   cast          5175 non-null   object
 9   director      5175 non-null   object
 10  keywords      5175 non-null   object
 11  release_year  5175 non-null   int32
dtypes: float64(2), int32(2), int64(1), object(7)
memory usage: 444.9+ KB

In [28]:
tmdb_merged_df.columns

Index(['tmdb_id', 'title', 'language', 'genres', 'popularity', 'vote_average',
       'vote_count', 'overview', 'cast', 'director', 'keywords',
       'release_year'],
      dtype='object')

In [29]:
genre_df=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\genre_tmdb.csv")

In [30]:
genre_df.head(20)

    Unnamed: 0  genre_id      genre_names
0            0        28           Action
1            1        12        Adventure
2            2        16        Animation
3            3        35           Comedy
4            4        80            Crime
5            5        99      Documentary
6            6        18            Drama
7            7     10751           Family
8            8        14          Fantasy
9            9        36          History
10          10        27           Horror
11          11     10402            Music
12          12      9648          Mystery
13          13     10749          Romance
14          14       878  Science Fiction
15          15     10770         TV Movie
16          16        53         Thriller
17          17     10752              War
18          18        37          Western

In [31]:
movie_genre_df=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\archive (3)\ml-100k\u.genre",
                           header=None,
                           sep="|",
                           names=["genres","genre_id"])

In [32]:
movie_genre_df.head(20)

         genres  genre_id
0       unknown         0
1        Action         1
2     Adventure         2
3     Animation         3
4    Children's         4
5        Comedy         5
6         Crime         6
7   Documentary         7
8         Drama         8
9       Fantasy         9
10    Film-Noir        10
11       Horror        11
12      Musical        12
13      Mystery        13
14      Romance        14
15       Sci-Fi        15
16     Thriller        16
17          War        17
18      Western        18

In [33]:
genre_df=genre_df.drop(columns=["Unnamed: 0"])

In [34]:
genre_df.head(20)

    genre_id      genre_names
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         TV Movie
16        53         Thriller
17     10752              War
18        37          Western

In [35]:
movie_genre_df["genres"]=movie_genre_df["genres"].str.lower()

In [36]:
genre_df["genre_names"]=genre_df["genre_names"].str.lower()

In [37]:
genre_df.head(20)

    genre_id      genre_names
0         28           action
1         12        adventure
2         16        animation
3         35           comedy
4         80            crime
5         99      documentary
6         18            drama
7      10751           family
8         14          fantasy
9         36          history
10        27           horror
11     10402            music
12      9648          mystery
13     10749          romance
14       878  science fiction
15     10770         tv movie
16        53         thriller
17     10752              war
18        37          western

In [38]:
GENRE_NORMALIZATION = {
    "science fiction": "sci-fi",
    "musical":"music",
    "family": "children",
    "children's": "children",
    "film-noir": "noir",
    "tv movie": "",
    "unknown":""
}

In [39]:
def normalize_genre(name):
    return GENRE_NORMALIZATION.get(name,name)

In [40]:
genre_df["genre_names"]=genre_df["genre_names"].apply(normalize_genre)

In [41]:
genre_df.head(20)

    genre_id  genre_names
0         28       action
1         12    adventure
2         16    animation
3         35       comedy
4         80        crime
5         99  documentary
6         18        drama
7      10751     children
8         14      fantasy
9         36      history
10        27       horror
11     10402        music
12      9648      mystery
13     10749      romance
14       878       sci-fi
15     10770
16        53     thriller
17     10752          war
18        37      western

In [42]:
genre_df=genre_df[genre_df["genre_names"]!=""]

In [43]:
tmdb_genre_map=dict(zip(genre_df["genre_id"],genre_df["genre_names"]))

In [44]:
def convert_genre_id(genre_list):
    names=[tmdb_genre_map.get(i,"") for i in genre_list]
    names=[g for g in names if g!=""]
    names=list(set(names))
    return " ".join(names)

In [45]:
import ast
tmdb_merged_df["genres"]=tmdb_merged_df["genres"].apply(ast.literal_eval)

In [46]:
tmdb_merged_df["genres"]=tmdb_merged_df["genres"].apply(convert_genre_id)

In [47]:
tmdb_merged_df.head(20)

,tmdb_id,title,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords,release_year
0,4247,Scary Movie,en,comedy,22.2560,6.388,7623,A familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...,2000
1,98,Gladiator,en,action adventure drama,18.2146,8.223,20647,"After the death of Emperor Marcus Aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir...",2000
2,4234,Scream 3,en,horror mystery,11.5470,6.007,3982,As bodies begin dropping around the Hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...,2000
3,11688,The Emperor's New Groove,en,animation comedy children fantasy adventure,11.2891,7.557,7218,Emperor Kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...,2000
4,77,Memento,en,thriller mystery,11.6323,8.176,16025,Leonard Shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...,2000
5,107,Snatch,en,comedy crime,11.9698,7.817,9832,"Unscrupulous boxing promoters, violent bookies...",jasonstatham alanford stephengraham bradpitt d...,guyritchie,robbery trailer park england gypsy gambling ba...,2000
6,1359,American Psycho,en,thriller drama crime,11.8479,7.407,12107,A wealthy New York investment banking executiv...,christianbale justintheroux joshlucas billsage...,maryharron,new york city based on novel or book businessm...,2000
7,8871,How the Grinch Stole Christmas,en,comedy fantasy children,8.2609,6.782,8207,The Grinch decides to rob Whoville of Christma...,jimcarrey taylormomsen jeffreytambor christine...,ronhoward,new love based on novel or book holiday christ...,2000
8,8358,Cast Away,en,adventure drama,8.8856,7.660,12135,"Chuck Noland, a top international manager for ...",tomhanks helenhunt chrisnoth paulsanchez lariw...,robertzemeckis,exotic island suicide attempt volleyball survi...,2000
9,9532,Final Destination,en,horror,7.8918,6.630,6566,After a teenager has a terrifying vision of hi...,devonsawa alilarter kerrsmith kristencloke dan...,jameswong,airport time travel omen premonition airplane ...,2000
10,4327,Charlie's Angels,en,comedy action adventure,7.4386,5.852,4461,The captivating crime-fighting trio who are ma...,camerondiaz drewbarrymore lucyliu billmurray s...,mcg,martial arts undercover agent spy secret agent...,2000
11,1900,Traffic,en,thriller drama crime,8.0909,7.082,2364,An exploration of the United States of America...,michaeldouglas beniciodeltoro catherinezeta-jo...,stevensoderbergh,drug dealer daughter mother drug abuse drug sm...,2000
12,955,Mission: Impossible II,en,thriller action adventure,8.3880,6.141,7465,With computer genius Luther Stickell at his si...,tomcruise dougrayscott thandiwenewton vingrham...,johnwoo,dying and death mask island central intelligen...,2000
13,1443,The Virgin Suicides,en,drama romance,7.1585,7.131,3563,A group of male friends become obsessed with f...,kirstendunst joshhartnett jameswoods kathleent...,sofiacoppola,suicide based on novel or book michigan suicid...,2000
14,2024,The Patriot,en,war history drama action,6.4434,7.183,4244,After proving himself on the field of battle i...,melgibson heathledger joelyrichardson jasonisa...,rolandemmerich,daughter mission general southern usa loss of ...,2000
15,3981,What Women Want,en,comedy romance,5.7584,6.448,4318,Advertising executive Nick Marshall is as cock...,melgibson helenhunt marisatomei alanalda ashle...,nancymeyers,telepathy romcom womanizer single father super...,2000
16,2123,"Me, Myself & Irene",en,comedy,6.8674,6.611,4184,Rhode Island State Trooper Charlie Baileygates...,jimcarrey renéezellweger anthonyanderson mongo...,peterfarrelly,schizophrenia road trip ex-cop aftercreditssti...,2000
17,134,"O Brother, Where Art Thou?",en,comedy adventure crime,6.1770,7.324,4530,"In the deep south during the 1930s, three esca...",georgeclooney johnturturro timblakenelson john...,joelcoen,music record country music based on novel or b...,2000
18,9741,Unbreakable,en,thriller mystery drama,6.3022,7.143,9827,An ordinary man makes an extraordinary discove...,brucewillis samuell.jackson robinwright spence...,m.nightshyamalan,"philadelphia, pennsylvania parent child relati...",2000
19,7443,Chicken Run,en,comedy animation children,6.1791,6.838,5362,The creators of Wallace & Gromit bring you an ...,juliasawalha melgibson imeldastaunton janehorr...,nickpark,farm northern england escape raf (royal air fo...,2000

In [48]:
print(type(tmdb_merged_df["genres"].iloc[0]))

<class 'str'>

In [49]:
print(tmdb_merged_df["genres"].iloc[0])
print(type(tmdb_merged_df["genres"].iloc[0]))

comedy
<class 'str'>

In [50]:
tmdb_merged_df["genres"]=tmdb_merged_df["genres"].apply(lambda x: x.split())

In [51]:
tmdb_merged_df.to_pickle(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb1.pkl")

In [52]:
import pandas as pd
df=pd.read_pickle(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\raw\tmdb1.pkl")

In [53]:
df.columns

Index(['tmdb_id', 'title', 'language', 'genres', 'popularity', 'vote_average',
       'vote_count', 'overview', 'cast', 'director', 'keywords',
       'release_year'],
      dtype='object')

In [54]:
df.isnull().sum()

tmdb_id         0
title           0
language        0
genres          0
popularity      0
vote_average    0
vote_count      0
overview        0
cast            0
director        0
keywords        0
release_year    0
dtype: int64

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tmdb_id       5175 non-null   int64
 1   title         5175 non-null   object
 2   language      5175 non-null   object
 3   genres        5175 non-null   object
 4   popularity    5175 non-null   float64
 5   vote_average  5175 non-null   float64
 6   vote_count    5175 non-null   int32
 7   overview      5175 non-null   object
 8   cast          5175 non-null   object
 9   director      5175 non-null   object
 10  keywords      5175 non-null   object
 11  release_year  5175 non-null   int32
dtypes: float64(2), int32(2), int64(1), object(7)
memory usage: 444.9+ KB

In [56]:
df1=pd.read_pickle(r"C:\Users\aksha\OneDrive\Desktop\ARS(advanced recommendation system)\data\processed\movielens_for_scaling.pkl")

In [57]:
df1.head(20)

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,M,Kolya (1996),[Comedy],writer
1,186,302,3.0,39,F,L.A. Confidential (1997),"[Thriller, Mystery, Film-Noir, Crime]",executive
2,22,377,1.0,25,M,Heavyweights (1994),"[Family, Comedy]",writer
3,244,51,2.0,28,M,Legends of the Fall (1994),"[War, Drama, Western, Romance]",technician
4,166,346,1.0,47,M,Jackie Brown (1997),"[Drama, Crime]",educator
5,298,474,4.0,44,M,Dr. Strangelove or: How I Learned to Stop Worr...,"[War, Science Fiction]",executive
6,115,265,2.0,31,M,"Hunt for Red October, The (1990)","[Thriller, Action]",engineer
7,253,465,5.0,26,F,"Jungle Book, The (1994)","[Adventure, Family, Romance]",librarian
8,305,451,3.0,23,M,Grease (1978),"[Romance, Music, Comedy]",programmer
9,6,86,3.0,42,M,"Remains of the Day, The (1993)",[Drama],executive
10,62,257,2.0,27,F,Men in Black (1997),"[Adventure, Science Fiction, Action, Comedy]",administrator
11,286,1014,5.0,27,M,Romy and Michele's High School Reunion (1997),[Comedy],student
12,200,222,5.0,40,M,Star Trek: First Contact (1996),"[Adventure, Science Fiction, Action]",programmer
13,210,40,3.0,39,M,"To Wong Foo, Thanks for Everything! Julie Newm...",[Comedy],engineer
14,224,29,3.0,31,F,Batman Forever (1995),"[Adventure, Action, Crime, Comedy]",educator
15,303,785,3.0,19,M,Only You (1994),"[Romance, Comedy]",student
16,122,387,5.0,32,F,"Age of Innocence, The (1993)",[Drama],writer
17,194,274,2.0,38,M,Sabrina (1995),"[Romance, Comedy]",administrator
18,291,1042,4.0,19,M,Just Cause (1995),"[Thriller, Mystery]",student
19,234,1184,2.0,60,M,"Endless Summer 2, The (1994)",[Documentary],retired

In [58]:
df.head(20)

,tmdb_id,title,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords,release_year
0,4247,Scary Movie,en,[comedy],22.2560,6.388,7623,A familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...,2000
1,98,Gladiator,en,"[action, adventure, drama]",18.2146,8.223,20647,"After the death of Emperor Marcus Aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir...",2000
2,4234,Scream 3,en,"[horror, mystery]",11.5470,6.007,3982,As bodies begin dropping around the Hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...,2000
3,11688,The Emperor's New Groove,en,"[animation, comedy, children, fantasy, adventure]",11.2891,7.557,7218,Emperor Kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...,2000
4,77,Memento,en,"[thriller, mystery]",11.6323,8.176,16025,Leonard Shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...,2000
5,107,Snatch,en,"[comedy, crime]",11.9698,7.817,9832,"Unscrupulous boxing promoters, violent bookies...",jasonstatham alanford stephengraham bradpitt d...,guyritchie,robbery trailer park england gypsy gambling ba...,2000
6,1359,American Psycho,en,"[thriller, drama, crime]",11.8479,7.407,12107,A wealthy New York investment banking executiv...,christianbale justintheroux joshlucas billsage...,maryharron,new york city based on novel or book businessm...,2000
7,8871,How the Grinch Stole Christmas,en,"[comedy, fantasy, children]",8.2609,6.782,8207,The Grinch decides to rob Whoville of Christma...,jimcarrey taylormomsen jeffreytambor christine...,ronhoward,new love based on novel or book holiday christ...,2000
8,8358,Cast Away,en,"[adventure, drama]",8.8856,7.660,12135,"Chuck Noland, a top international manager for ...",tomhanks helenhunt chrisnoth paulsanchez lariw...,robertzemeckis,exotic island suicide attempt volleyball survi...,2000
9,9532,Final Destination,en,[horror],7.8918,6.630,6566,After a teenager has a terrifying vision of hi...,devonsawa alilarter kerrsmith kristencloke dan...,jameswong,airport time travel omen premonition airplane ...,2000
10,4327,Charlie's Angels,en,"[comedy, action, adventure]",7.4386,5.852,4461,The captivating crime-fighting trio who are ma...,camerondiaz drewbarrymore lucyliu billmurray s...,mcg,martial arts undercover agent spy secret agent...,2000
11,1900,Traffic,en,"[thriller, drama, crime]",8.0909,7.082,2364,An exploration of the United States of America...,michaeldouglas beniciodeltoro catherinezeta-jo...,stevensoderbergh,drug dealer daughter mother drug abuse drug sm...,2000
12,955,Mission: Impossible II,en,"[thriller, action, adventure]",8.3880,6.141,7465,With computer genius Luther Stickell at his si...,tomcruise dougrayscott thandiwenewton vingrham...,johnwoo,dying and death mask island central intelligen...,2000
13,1443,The Virgin Suicides,en,"[drama, romance]",7.1585,7.131,3563,A group of male friends become obsessed with f...,kirstendunst joshhartnett jameswoods kathleent...,sofiacoppola,suicide based on novel or book michigan suicid...,2000
14,2024,The Patriot,en,"[war, history, drama, action]",6.4434,7.183,4244,After proving himself on the field of battle i...,melgibson heathledger joelyrichardson jasonisa...,rolandemmerich,daughter mission general southern usa loss of ...,2000
15,3981,What Women Want,en,"[comedy, romance]",5.7584,6.448,4318,Advertising executive Nick Marshall is as cock...,melgibson helenhunt marisatomei alanalda ashle...,nancymeyers,telepathy romcom womanizer single father super...,2000
16,2123,"Me, Myself & Irene",en,[comedy],6.8674,6.611,4184,Rhode Island State Trooper Charlie Baileygates...,jimcarrey renéezellweger anthonyanderson mongo...,peterfarrelly,schizophrenia road trip ex-cop aftercreditssti...,2000
17,134,"O Brother, Where Art Thou?",en,"[comedy, adventure, crime]",6.1770,7.324,4530,"In the deep south during the 1930s, three esca...",georgeclooney johnturturro timblakenelson john...,joelcoen,music record country music based on novel or b...,2000
18,9741,Unbreakable,en,"[thriller, mystery, drama]",6.3022,7.143,9827,An ordinary man makes an extraordinary discove...,brucewillis samuell.jackson robinwright spence...,m.nightshyamalan,"philadelphia, pennsylvania parent child relati...",2000
19,7443,Chicken Run,en,"[comedy, animation, children]",6.1791,6.838,5362,The creators of Wallace & Gromit bring you an ...,juliasawalha melgibson imeldastaunton janehorr...,nickpark,farm northern england escape raf (royal air fo...,2000

In [59]:
df["genres"].unique

<bound method Series.unique of 0                                                [comedy]
1                              [action, adventure, drama]
2                                       [horror, mystery]
3       [animation, comedy, children, fantasy, adventure]
4                                     [thriller, mystery]
                              ...
5170                                   [thriller, action]
5171                             [comedy, drama, romance]
5172                                       [music, drama]
5173                                   [thriller, horror]
5174                                    [thriller, drama]
Name: genres, Length: 5175, dtype: object>

In [60]:
df1["genre_label"]=df1["genre_label"].apply(lambda lst: [x.lower() for x in lst])

In [61]:
unique_genres=df["genres"].str.split().explode().unique

In [62]:
print(unique_genres)

<bound method Series.unique of 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
5170   NaN
5171   NaN
5172   NaN
5173   NaN
5174   NaN
Name: genres, Length: 5175, dtype: float64>

In [63]:
GENRE_NORMALIZATION = {
    "science fiction": "sci-fi",
    "musical":"music",
    "family": "children",
    "children's": "children",
    "film-noir": "noir",
    "tv movie": "",
    "unknown":""
}

In [64]:
def normalize_genre(lt):
    result=[]
    for g in lt:
        g=GENRE_NORMALIZATION.get(g,g)
        if g!="":
            result.append(g)
    return list(set(result))

In [65]:
df1["genre_label"]=df1["genre_label"].apply(normalize_genre)

In [66]:
df1.head(6)

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,M,Kolya (1996),[comedy],writer
1,186,302,3.0,39,F,L.A. Confidential (1997),"[thriller, mystery, noir, crime]",executive
2,22,377,1.0,25,M,Heavyweights (1994),"[comedy, children]",writer
3,244,51,2.0,28,M,Legends of the Fall (1994),"[western, war, drama, romance]",technician
4,166,346,1.0,47,M,Jackie Brown (1997),"[drama, crime]",educator
5,298,474,4.0,44,M,Dr. Strangelove or: How I Learned to Stop Worr...,"[war, sci-fi]",executive

In [67]:
df1["title"]=df1["title"].str.lower()

In [82]:
df1.head(6)

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,1,kolya (1996),[comedy],writer
1,186,302,3.0,39,0,l.a. confidential (1997),"[thriller, mystery, noir, crime]",executive
2,22,377,1.0,25,1,heavyweights (1994),"[comedy, children]",writer
3,244,51,2.0,28,1,legends of the fall (1994),"[western, war, drama, romance]",technician
4,166,346,1.0,47,1,jackie brown (1997),"[drama, crime]",educator
5,298,474,4.0,44,1,dr. strangelove or: how i learned to stop worr...,"[war, sci-fi]",executive

In [83]:
df1["genre_label"]=df1["genre_label"].apply(lambda lst:" ".join(lst))

In [84]:
df1.head(6)

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,1,kolya (1996),comedy,writer
1,186,302,3.0,39,0,l.a. confidential (1997),thriller mystery noir crime,executive
2,22,377,1.0,25,1,heavyweights (1994),comedy children,writer
3,244,51,2.0,28,1,legends of the fall (1994),western war drama romance,technician
4,166,346,1.0,47,1,jackie brown (1997),drama crime,educator
5,298,474,4.0,44,1,dr. strangelove or: how i learned to stop worr...,war sci-fi,executive

In [68]:
df["title"]=df["title"].str.lower()

In [69]:
df["overview"]=df["overview"].str.lower()

In [70]:
df["cast"]=df["cast"].str.lower()

In [71]:
df["director"]=df["director"].str.lower()

In [72]:
df["keywords"]=df["keywords"].str.lower()

In [73]:
df.head(20)

,tmdb_id,title,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords,release_year
0,4247,scary movie,en,[comedy],22.2560,6.388,7623,a familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...,2000
1,98,gladiator,en,"[action, adventure, drama]",18.2146,8.223,20647,"after the death of emperor marcus aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir...",2000
2,4234,scream 3,en,"[horror, mystery]",11.5470,6.007,3982,as bodies begin dropping around the hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...,2000
3,11688,the emperor's new groove,en,"[animation, comedy, children, fantasy, adventure]",11.2891,7.557,7218,emperor kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...,2000
4,77,memento,en,"[thriller, mystery]",11.6323,8.176,16025,leonard shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...,2000
5,107,snatch,en,"[comedy, crime]",11.9698,7.817,9832,"unscrupulous boxing promoters, violent bookies...",jasonstatham alanford stephengraham bradpitt d...,guyritchie,robbery trailer park england gypsy gambling ba...,2000
6,1359,american psycho,en,"[thriller, drama, crime]",11.8479,7.407,12107,a wealthy new york investment banking executiv...,christianbale justintheroux joshlucas billsage...,maryharron,new york city based on novel or book businessm...,2000
7,8871,how the grinch stole christmas,en,"[comedy, fantasy, children]",8.2609,6.782,8207,the grinch decides to rob whoville of christma...,jimcarrey taylormomsen jeffreytambor christine...,ronhoward,new love based on novel or book holiday christ...,2000
8,8358,cast away,en,"[adventure, drama]",8.8856,7.660,12135,"chuck noland, a top international manager for ...",tomhanks helenhunt chrisnoth paulsanchez lariw...,robertzemeckis,exotic island suicide attempt volleyball survi...,2000
9,9532,final destination,en,[horror],7.8918,6.630,6566,after a teenager has a terrifying vision of hi...,devonsawa alilarter kerrsmith kristencloke dan...,jameswong,airport time travel omen premonition airplane ...,2000
10,4327,charlie's angels,en,"[comedy, action, adventure]",7.4386,5.852,4461,the captivating crime-fighting trio who are ma...,camerondiaz drewbarrymore lucyliu billmurray s...,mcg,martial arts undercover agent spy secret agent...,2000
11,1900,traffic,en,"[thriller, drama, crime]",8.0909,7.082,2364,an exploration of the united states of america...,michaeldouglas beniciodeltoro catherinezeta-jo...,stevensoderbergh,drug dealer daughter mother drug abuse drug sm...,2000
12,955,mission: impossible ii,en,"[thriller, action, adventure]",8.3880,6.141,7465,with computer genius luther stickell at his si...,tomcruise dougrayscott thandiwenewton vingrham...,johnwoo,dying and death mask island central intelligen...,2000
13,1443,the virgin suicides,en,"[drama, romance]",7.1585,7.131,3563,a group of male friends become obsessed with f...,kirstendunst joshhartnett jameswoods kathleent...,sofiacoppola,suicide based on novel or book michigan suicid...,2000
14,2024,the patriot,en,"[war, history, drama, action]",6.4434,7.183,4244,after proving himself on the field of battle i...,melgibson heathledger joelyrichardson jasonisa...,rolandemmerich,daughter mission general southern usa loss of ...,2000
15,3981,what women want,en,"[comedy, romance]",5.7584,6.448,4318,advertising executive nick marshall is as cock...,melgibson helenhunt marisatomei alanalda ashle...,nancymeyers,telepathy romcom womanizer single father super...,2000
16,2123,"me, myself & irene",en,[comedy],6.8674,6.611,4184,rhode island state trooper charlie baileygates...,jimcarrey renéezellweger anthonyanderson mongo...,peterfarrelly,schizophrenia road trip ex-cop aftercreditssti...,2000
17,134,"o brother, where art thou?",en,"[comedy, adventure, crime]",6.1770,7.324,4530,"in the deep south during the 1930s, three esca...",georgeclooney johnturturro timblakenelson john...,joelcoen,music record country music based on novel or b...,2000
18,9741,unbreakable,en,"[thriller, mystery, drama]",6.3022,7.143,9827,an ordinary man makes an extraordinary discove...,brucewillis samuell.jackson robinwright spence...,m.nightshyamalan,"philadelphia, pennsylvania parent child relati...",2000
19,7443,chicken run,en,"[comedy, animation, children]",6.1791,6.838,5362,the creators of wallace & gromit bring you an ...,juliasawalha melgibson imeldastaunton janehorr...,nickpark,farm northern england escape raf (royal air fo...,2000

In [74]:
df["genres"]=df["genres"].apply(lambda lst : " ".join(lst))

In [75]:
df.head(20)

,tmdb_id,title,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords,release_year
0,4247,scary movie,en,comedy,22.2560,6.388,7623,a familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...,2000
1,98,gladiator,en,action adventure drama,18.2146,8.223,20647,"after the death of emperor marcus aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir...",2000
2,4234,scream 3,en,horror mystery,11.5470,6.007,3982,as bodies begin dropping around the hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...,2000
3,11688,the emperor's new groove,en,animation comedy children fantasy adventure,11.2891,7.557,7218,emperor kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...,2000
4,77,memento,en,thriller mystery,11.6323,8.176,16025,leonard shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...,2000
5,107,snatch,en,comedy crime,11.9698,7.817,9832,"unscrupulous boxing promoters, violent bookies...",jasonstatham alanford stephengraham bradpitt d...,guyritchie,robbery trailer park england gypsy gambling ba...,2000
6,1359,american psycho,en,thriller drama crime,11.8479,7.407,12107,a wealthy new york investment banking executiv...,christianbale justintheroux joshlucas billsage...,maryharron,new york city based on novel or book businessm...,2000
7,8871,how the grinch stole christmas,en,comedy fantasy children,8.2609,6.782,8207,the grinch decides to rob whoville of christma...,jimcarrey taylormomsen jeffreytambor christine...,ronhoward,new love based on novel or book holiday christ...,2000
8,8358,cast away,en,adventure drama,8.8856,7.660,12135,"chuck noland, a top international manager for ...",tomhanks helenhunt chrisnoth paulsanchez lariw...,robertzemeckis,exotic island suicide attempt volleyball survi...,2000
9,9532,final destination,en,horror,7.8918,6.630,6566,after a teenager has a terrifying vision of hi...,devonsawa alilarter kerrsmith kristencloke dan...,jameswong,airport time travel omen premonition airplane ...,2000
10,4327,charlie's angels,en,comedy action adventure,7.4386,5.852,4461,the captivating crime-fighting trio who are ma...,camerondiaz drewbarrymore lucyliu billmurray s...,mcg,martial arts undercover agent spy secret agent...,2000
11,1900,traffic,en,thriller drama crime,8.0909,7.082,2364,an exploration of the united states of america...,michaeldouglas beniciodeltoro catherinezeta-jo...,stevensoderbergh,drug dealer daughter mother drug abuse drug sm...,2000
12,955,mission: impossible ii,en,thriller action adventure,8.3880,6.141,7465,with computer genius luther stickell at his si...,tomcruise dougrayscott thandiwenewton vingrham...,johnwoo,dying and death mask island central intelligen...,2000
13,1443,the virgin suicides,en,drama romance,7.1585,7.131,3563,a group of male friends become obsessed with f...,kirstendunst joshhartnett jameswoods kathleent...,sofiacoppola,suicide based on novel or book michigan suicid...,2000
14,2024,the patriot,en,war history drama action,6.4434,7.183,4244,after proving himself on the field of battle i...,melgibson heathledger joelyrichardson jasonisa...,rolandemmerich,daughter mission general southern usa loss of ...,2000
15,3981,what women want,en,comedy romance,5.7584,6.448,4318,advertising executive nick marshall is as cock...,melgibson helenhunt marisatomei alanalda ashle...,nancymeyers,telepathy romcom womanizer single father super...,2000
16,2123,"me, myself & irene",en,comedy,6.8674,6.611,4184,rhode island state trooper charlie baileygates...,jimcarrey renéezellweger anthonyanderson mongo...,peterfarrelly,schizophrenia road trip ex-cop aftercreditssti...,2000
17,134,"o brother, where art thou?",en,comedy adventure crime,6.1770,7.324,4530,"in the deep south during the 1930s, three esca...",georgeclooney johnturturro timblakenelson john...,joelcoen,music record country music based on novel or b...,2000
18,9741,unbreakable,en,thriller mystery drama,6.3022,7.143,9827,an ordinary man makes an extraordinary discove...,brucewillis samuell.jackson robinwright spence...,m.nightshyamalan,"philadelphia, pennsylvania parent child relati...",2000
19,7443,chicken run,en,comedy animation children,6.1791,6.838,5362,the creators of wallace & gromit bring you an ...,juliasawalha melgibson imeldastaunton janehorr...,nickpark,farm northern england escape raf (royal air fo...,2000

In [76]:
df1["gender"]=df1["gender"].map({"M":1,"F":0})

In [77]:
df1.head()

,user_id,item_id,rating,age,gender,title,genre_label,occupation
0,196,242,3.0,49,1,kolya (1996),[comedy],writer
1,186,302,3.0,39,0,l.a. confidential (1997),"[thriller, mystery, noir, crime]",executive
2,22,377,1.0,25,1,heavyweights (1994),"[comedy, children]",writer
3,244,51,2.0,28,1,legends of the fall (1994),"[western, war, drama, romance]",technician
4,166,346,1.0,47,1,jackie brown (1997),"[drama, crime]",educator

In [78]:
df["cast1"]=df["cast"].str.replace(" ","")

In [79]:
df.head()

,tmdb_id,title,language,genres,popularity,vote_average,vote_count,overview,cast,director,keywords,release_year,cast1
0,4247,scary movie,en,comedy,22.2560,6.388,7623,a familiar-looking group of teenagers find the...,annafaris reginahall marlonwayans shawnwayans ...,keenenivorywayans,high school psychopath garage satire parody cr...,2000,annafarisreginahallmarlonwayansshawnwayansjona...
1,98,gladiator,en,action adventure drama,18.2146,8.223,20647,"after the death of emperor marcus aurelius, hi...",russellcrowe joaquinphoenix connienielsen oliv...,ridleyscott,"gladiator rome, italy arena senate roman empir...",2000,russellcrowejoaquinphoenixconnienielsenoliverr...
2,4234,scream 3,en,horror mystery,11.5470,6.007,3982,as bodies begin dropping around the hollywood ...,nevecampbell courteneycox davidarquette patric...,wescraven,mask isolation movie business ex-cop sequel se...,2000,nevecampbellcourteneycoxdavidarquettepatrickde...
3,11688,the emperor's new groove,en,animation comedy children fantasy adventure,11.2891,7.557,7218,emperor kuzco is turned into a llama by his ex...,davidspade johngoodman earthakitt patrickwarbu...,markdindal,central and south america kingdom birthday per...,2000,davidspadejohngoodmanearthakittpatrickwarburto...
4,77,memento,en,thriller mystery,11.6323,8.176,16025,leonard shelby is tracking down the man who ra...,guypearce carrie-annemoss joepantoliano markbo...,christophernolan,drug dealer amnesia insulin tattoo waitress mo...,2000,guypearcecarrie-annemossjoepantolianomarkboone...

In [85]:
df.columns

Index(['tmdb_id', 'title', 'language', 'genres', 'popularity', 'vote_average',
       'vote_count', 'overview', 'cast', 'director', 'keywords',
       'release_year', 'cast1'],
      dtype='object')

In [87]:
df=df.drop(columns=["cast1"])

In [88]:
df.columns

Index(['tmdb_id', 'title', 'language', 'genres', 'popularity', 'vote_average',
       'vote_count', 'overview', 'cast', 'director', 'keywords',
       'release_year'],
      dtype='object')

In [89]:
df["combined_features"]=(df["genres"]+" "+df["cast"]+" "+df["director"]+" "+df["overview"]+" "+df["keywords"])

In [90]:
df["combined_features"]

0       comedy annafaris reginahall marlonwayans shawn...
1       action adventure drama russellcrowe joaquinpho...
2       horror mystery nevecampbell courteneycox david...
3       animation comedy children fantasy adventure da...
4       thriller mystery guypearce carrie-annemoss joe...
                              ...
5170    thriller action saidhanshika kabirduhansingh s...
5171    comedy drama romance atharvaamurali fahadhfaas...
5172    music drama snehaasesh kabervasuki sruthi sisu...
5173    thriller horror f.j. ayraa chandhinitamilarasa...
5174    thriller drama m.sasikumar chaithrajachar guru...
Name: combined_features, Length: 5175, dtype: object

In [91]:
df.isnull().sum()

tmdb_id              0
title                0
language             0
genres               0
popularity           0
vote_average         0
vote_count           0
overview             0
cast                 0
director             0
keywords             0
release_year         0
combined_features    0
dtype: int64

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5175 entries, 0 to 5174
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tmdb_id            5175 non-null   int64
 1   title              5175 non-null   object
 2   language           5175 non-null   object
 3   genres             5175 non-null   object
 4   popularity         5175 non-null   float64
 5   vote_average       5175 non-null   float64
 6   vote_count         5175 non-null   int32
 7   overview           5175 non-null   object
 8   cast               5175 non-null   object
 9   director           5175 non-null   object
 10  keywords           5175 non-null   object
 11  release_year       5175 non-null   int32
 12  combined_features  5175 non-null   object
dtypes: float64(2), int32(2), int64(1), object(8)
memory usage: 485.3+ KB

In [ ]:
df.to_pickle(r"